### PR TITLE
Added test scenarios for restarting job with multiple online devices - second part

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: ct-anaalbic <Ana.Albic@comtrade.com>

Brief description of the PR.
Added second part of scenarios for restarting job with multiple online devices.

**Related Issue**
This PR fixes/closes part of issue #2662

**Description of the solution adopted**
This PR represents second part of JobEngineService integration tests for restarting job with multiple online devices. In feature file JobEngineServiceRestartOnlineDeviceI9n.feature the scenarios for restarting job with multiple targets and one or more steps are added. Also, in this scenarios, job is restarted with valid and invalid proper parameters. 

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by ct-anaalbic** [comment]
Hi @Coduz,

I tried to increase resources on travis, but it was unsuccessful. Instead of that, I used refactoring of tags. So with this tags in .feature files for JobEngine Service, all tests passed without errors.
Can you, please, check this code and merge if everything is ok? 

Best regards,

_Ana_

**Review by Coduz — APPROVED** [review]

**Comment by Coduz** [comment]
Travis CI seems not picking up changes and start the build.
This is the successful build triggered manually: https://travis-ci.org/eclipse/kapua/builds/584559386

**Comment by ct-anaalbic** [comment]
Hi @Coduz 

I'm working on some changes in this PR, so after that I will push that. I hope after that tests on travis will run again. 

Regards,
_Ana_

**Comment by ct-anaalbic** [comment]
Hi @Coduz, 

As we said before, Job Engine Service has big number of tests. So, I separated tags in .feature files for job engine, and also I made changes in travis.yml file in this PR. So, you can check it and if everything passing without errors you can merge.

Best regards, 
_Ana_

**Comment by LeoNerdoG** [comment]
@Coduz everything is OK now, can you pelase merge this? 😄

**Review by Coduz — APPROVED** [review]

**Pull request merged**
