### PR TITLE
Added integration tests for Scheduler Service 

### PR DESCRIPTION
**Pull request by code-incubus**
Added several test for scheduler services.

Signed-off-by: code-incubus <nemanja.milutinovic@comtrade.com>

Brief description of the PR.
Added integration test scenarios for scheduler services.

**Related Issue**
This PR fixes/closes part of issue #2757  

**Description of the solution adopted**
Added test scenarios for scheduler services. 
- Simple interval triggering
- Cron interval triggering

**Screenshots**
/
**Any side note on the changes made**
/

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I have checked the tests and they look ok. Can you please merge the PR when you can?

**Review by Coduz — APPROVED** [review]

**Comment by Coduz** [comment]
Hi @LeoNerdoG 

This PR seems to not have run the CI on Travis.
Do you know why?

@code-incubus can you please rebase and push force your code so the CI Travis build may start?

Regards, 

_Alberto_

**Comment by code-incubus** [comment]
I have already rebased and pushed my code but still nothing...
Maybe I should to close this PR and reopen it? On my fork, Travis is running ok.
@Coduz

**Comment by Coduz** [comment]
Hi @code-incubus ,

I've seen that in the request log of travis there is this message:

Screen Shot 2020-01-09 at 10 14 45 AM

Which is your commit message, but is not recognized by Travis as a PR. I've checked out your branch and pushed to my fork and the build started without problems. 

You have any idea why it is reporting that error message?

Regards, 

_Alberto_

**Comment by code-incubus** [comment]
Hey @Coduz 
Where did you find that error message?

**Comment by Coduz** [comment]
`More Options` > `Requests`

There is the menu on the top right corner, just above the table

**Comment by Coduz** [comment]
I've tried to create a PR from my fork and it worked. 
Then I came here again and found that the PR build has actually started! 

Likely Travis had some problem 🤷‍♂ 

EDIT: checking travis is using the build run for my test PR #2812 as test also for this PR.... So we'll wait until completes and if the build report is still linked we will merge this PR!

**Comment by Coduz** [comment]
No, it didn't work.
Can you please try to open a new PR? That should work

**Comment by code-incubus** [comment]
I closing this PR because of some error occurred on Travis.

**Pull request closed without merging**
