### PR TITLE
⬆️  [Dependencies] Upgrade Artemis from 2.31.2 to 2.38.0

### PR DESCRIPTION
**Pull request by riccardomodanese**
Brief description of the PR.
see description

**Related Issue**
none

**Description of the solution adopted**
just upgrade dependency

**Screenshots**
none

**Any side note on the changes made**
none

### CODE REVIEW

**Review by Coduz — APPROVED** [review]

**Comment by riccardomodanese** [comment]
upgraded versions
- Netty to 4.1.114.Final
- Logback 1.5.12
- Slf4J to 2.0.16

**Pull request merged**
