### PR TITLE
Added Tests For Scheduler And Endpoint Permissions

### PR DESCRIPTION
**Pull request by zanpizmoht**
Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

Added 3 tests for user permissions managing with Endpoints and Scheduler.

**Related Issue**
This PR fixes/closes part of issue #126 

**Description of the solution adopted**
In this pull request I added 3 test scenarios for user permissions. The scenarios were added to `UserPermissionI9n.feature` file. The scenarios are:

1. Add Scheduler Permissions Without Job Permissions
2. Add Scheduler Permissions With Job Permissions
3. Add Endpoint Permission To The User

I also modified `CucPermission.java` class so you can add targetScopeId to cucumber scenario directly as an integer.

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by lorthirk** [comment]
Hi @zanpizmoht, thanks for the contribution!

Have you signed the [Eclipse ECA](https://www.eclipse.org/legal/ECA.php) already?

**Comment by LeoNerdoG** [comment]
Hey @lorthirk,
there was a incosisntecy with the e-mails (sign off was made with different e-mail). 
We have resolved this and now it should be OK 😄

**Comment by lorthirk** [comment]
Great! 😄

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I have checked this PR and it looks OK, cna you take a look and merge if everything is OK? Also the tests have succesfully passed.

**Review by Coduz — APPROVED** [review]

**Pull request merged**
