### PR TITLE
:feat: upgrade spring-springboot-camel-artemis

### PR DESCRIPTION
**Pull request by riccardomodanese**
Brief description of the PR.
upgrade Spring/Springboot/Camel/Artemis dependencies

**Related Issue**
none

**Description of the solution adopted**
none

**Screenshots**
none

**Any side note on the changes made**
none

### CODE REVIEW

**Comment by riccardomodanese** [comment]
waiting for #4087

**Review by Coduz — APPROVED** [review]

**Comment by riccardomodanese** [comment]
replaced by newest

**Pull request closed without merging**
