### PR TITLE
Added tests for Device service

### PR DESCRIPTION
**Pull request by zanpizmoht**
Added tests for adding, deleting, editing and filtering devices.

Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

Test scenarios for Devices are added in this PR.

**Related Issue**
_None_

**Description of the solution adopted**
Test scenarios that are added in this PR are checking functionalities regarding Devices. All scenarios are added to `DeviceServiceI9n.feature`. Scenarios are testing if Devices are correctly created, edited and deleted. It is also checking if searching by filter for devices works correctly.

**Screenshots**
/

### CODE REVIEW

**Review by Coduz — APPROVED** [review]

**Comment by Coduz** [comment]
CQ submitted: [CQ 21413](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21413)

**Review by LeoNerdoG — CHANGES_REQUESTED** [review]
Hi @zanpizmoht,
I have reviewed this PR and there are some changes that need to be made. 
Please address the comments when you can. 
Do not merge this PR until these things are properly addressed.

**Review by LeoNerdoG — CHANGES_REQUESTED** [review]
Hi @zanpizmoht,
I have reviewed this PR and there are some changes that need to be made. 
Please address the comments when you can. 
Do not merge this PR until these things are properly addressed.

**Review by LeoNerdoG — APPROVED** [review]
Hey @Coduz,
I have reviewed this PR and it looks OK now. You can put "QA Approved" label to it and merge it when CQ passes.

**Comment by Coduz** [comment]
[CQ Approved!](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21413#c5) 🎉

**Pull request merged**
