### PR TITLE
upload and apply button frozen if device is online 

### PR DESCRIPTION
**Pull request by ct-goranpalibrk**
Signed-off-by: CT\pgoran <goran.palibrk@comtrade.com>

### CODE REVIEW

**Comment by ct-goranpalibrk** [comment]
If device is null or ofline upload and apply button now is frozen in Snapshots tab in Devices view.

**Comment by LeoNerdoG** [comment]
I have verified tha this PR successfully fixes issue #1134 .

**Comment by muros-ct** [comment]
Simple one liner solution.
@LeoNerdoG if this solves issue, we can merge.
Thou it might still be a problem in case when device is disconnected and shown as connected in device grid. Is this solved by previous fixes? Please re-test.

**Comment by LeoNerdoG** [comment]
@muros-ct I have retested this and found out that this PR does not solve problem in this specific case (when device is disconnected and shown as connected in device grid). Although this was not one of the scenarios of issue #1134 I think it should also be corrected before merging.

**Comment by LeoNerdoG** [comment]
@muros-ct Goran and I have agreed that we will solve problem, you mentioned, later with a PR, which will solve not only issue with this button but with all others also - becuase problem you described is not directly connected to this button but is more general in its nature.

**Pull request merged**
