### PR TITLE
Added integration tests for Scheduler Service

### PR DESCRIPTION
**Pull request by code-incubus**
Signed-off-by: code-incubus <nemanja.milutinovic@comtrade.com>

Brief description of the PR.
Added integration test scenarios for scheduler services.

**Related Issue**
This PR fixes/closes part of issue #2757 

**Description of the solution adopted**
Added test scenarios for scheduler services.

Simple interval triggering
Cron interval triggering

**Screenshots**
/

**Any side note on the changes made**
/

### CODE REVIEW

**Comment by code-incubus** [comment]
Hi @Coduz,
I tried to create two new PR but Travis still remembers only your PR and that PR is shown (failed) as you see above.
It doesn't even start...

**Comment by Coduz** [comment]
This PR is still reporting the "Abuse detected"....
Could you please check with the Travis CI support?

**Comment by code-incubus** [comment]
I already text them about that. So, I'm waiting for feedback.

**Comment by code-incubus** [comment]
Hi @Coduz,
I got feedback from the Travis Support team.
Their system automatically flagged my account for possible abuse & that's fixed right now.
So, I'm going to close this PR and try to create another one and will see what's happening next.

**Pull request closed without merging**
