### PR TITLE
Refactoring of job engine service integration tests

### PR DESCRIPTION
**Pull request by ct-anaalbic**
Signed-off-by: Ana Albic <ana.albic@comtrade.com>

Brief description of the PR.
In this PR refactoring of job engine service is done.

**Related Issue**
This PR refactors pull requests for issue #2662 

**Description of the solution adopted**
Refactoring of job engine service is done. It means that all syntax errors are removed, and test are reorganized to be more stable, so Travis build is successful in more percentage. In this PR all .feature files about job engine service are changed and refactored, and also, smart wait is implemented, so tests are faster, also. 
**For this PR CQ is necessary.**

**Screenshots**
_None_

**Any side note on the changes made**
_None_

### CODE REVIEW

**Comment by LeoNerdoG** [comment]
Hey @Coduz,
I have checked this branch and eveerything looks ok. 
Also all the tests have successfully passed without problems so I think this can be merged when CQ is approved (this should not be a problem since we are dealing only with tests here).

**Comment by Coduz** [comment]
CQ submitted: [CQ 21388](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21388)

**Comment by LeoNerdoG** [comment]
Hi @Coduz,
I have reviewed this branch and it looks OK. Can you please merge it when CQ passes? 

Thanks,
Leo

**Review by LeoNerdoG — APPROVED** [review]

**Comment by Coduz** [comment]
CQ approved! https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21388#c6

**Review by Coduz — APPROVED** [review]

**Pull request merged**
