### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes grammatical errors.

### CODE REVIEW

**Review by LeoNerdoG — CHANGES_REQUESTED** [review]
Hey @geetha-rangaswamaiah,
there are some other gramatical errors to be fixed:
 - "{% hint style='info' %} Most of the...." (please fix this hint)
 - "Docker containers" title should be "Docker Containers"
 - you should also change the line "kapua/deployment/docker/docker-deploy.sh" becasue this is not true anymore. We have different docker deploy scripts for every system (win, unix)
 - same goes for " kapua/deployment/docker/docker-undeploy.sh" line
 - Title for "Starting OpenShift cluster" should be "Starting OpenShift Cluster"
 - ....

Please fix all other syntax errors and push the change to the branch/PR.

**Comment by Coduz** [comment]
Hi @geetha-rangaswamaiah,

can you please also integrate the feedback from @LeoNerdoG ??

Thanks,

_Alberto_

**Comment by ghost** [comment]
Hey, @Coduz. I'm not finding the branch. Can we please close this PR? I'll recreate it.

**Comment by LeoNerdoG** [comment]
Hey @geetha-rangaswamaiah, there is no need to close the PR, becasue you can just make another commit with the changes suggested above, squash and push and then we can merge it. GIT and GitHub are really cool for situations like these, so please keep working on this branch/PR.

**Comment by ghost** [comment]
I'd deleted the branch by mistake. It's showing as, "unknown repository". Could you please tell me how to recover the source branch of this PR? (I don't remember the branch name) Or is there any other way to commit changes? Thank you.

**Comment by LeoNerdoG** [comment]
Hey @geetha-rangaswamaiah,
do you have the branch stored locally?

**Comment by ghost** [comment]
Hi @LeoNerdoG, 

I'd created the branch in origin and then fetched it from there. 
```
git fetch origin
git checkout branch_name
```
I remember I'd deleted it from the origin. But when I list all my local branches, I'm not finding this branch.

**Comment by LeoNerdoG** [comment]
Ok then I recommend to close this PR and create new one. 
If you don't have branch on your local machine, there is no way to restore it.

**Comment by LeoNerdoG** [comment]
hey @geetha-rangaswamaiah, what is the status now regarding this PR? Will you close it and open a new one?

**Comment by ghost** [comment]
Yeah. Closed it.

**Pull request closed without merging**
