### PR TITLE
Changed checkstyle rule

### PR DESCRIPTION
**Pull request by LeoNerdoG**
I have changed checkstyle rule (added "|2021" in the header) as this will be needed in 2021.
@lorthirk can you please merge this so we can rebase all our PRs and other braches that are currently in review? Thank you! 

**Related Issue**
There is no related issue. 

**Description of the solution adopted**
/

**Any side note on the changes made**
/

Signed-off-by: Leonardo Gaube <leonardo.gaube@endava.com>

### CODE REVIEW

**Comment by lorthirk** [comment]
We should update all the 2020 copyrights to 2021 instead, so that headers with only `2020̀` become `2020, 2021` and older files become `201X, 2021`

**Review by lorthirk — CHANGES_REQUESTED** [review]
We should update all the 2020 copyrights to 2021 instead, so that headers with only `2020` become `2020, 2021` and older files become `201X, 2021`. New files will of course only have `2021`.

**Comment by LeoNerdoG** [comment]
Hey @lorthirk,
I can do this, but I will create several PRs in this case, becasue there are too much files for one PR as I am not a commiter.
I will do this in the folliowing days. Thanks for the comment 😄

**Comment by lorthirk** [comment]
@LeoNerdoG don't worry about that. I'll cover everything during the weekend.

**Comment by lorthirk** [comment]
I created #3189 so that you can base your branches on that one. Let's see if someone can review it quickly to also get it merged.

**Comment by LeoNerdoG** [comment]
I am closing this PR due to upper comment.

**Pull request closed without merging**
