### PR TITLE
Added tests for Tag service

### PR DESCRIPTION
**Pull request by zanpizmoht**
Added tests for creating, deleting and editing tags, and assigning tags to devices.

Signed-off-by: zanpizmoht <zan.pizmoht@comtrade.com>

Test scenarios for Tags are added in this PR.

**Related Issue**
_None_

**Description of the solution adopted**
Test scenarios that are added in this PR are checking functionalities regarding Tags. All scenarios are added to `TagService.feature`. Scenarios are testing if Tags are correctly created, edited and deleted.

**Screenshots**
/

### CODE REVIEW

**Comment by Coduz** [comment]
CQ submitted: [CQ 21397](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21397)

**Review by LeoNerdoG — CHANGES_REQUESTED** [review]
Hi @zanpizmoht,
I have reviewed this PR and there are some changes to be made. Can you please fix the commented stuff? Thanks!

**Review by LeoNerdoG — CHANGES_REQUESTED** [review]
Hi @zanpizmoht,
I have reviewed this PR and there are some changes to be made. Can you please fix the commented stuff? Thanks!

**Review by LeoNerdoG — APPROVED** [review]

**Comment by Coduz** [comment]
[CQ Approved!](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21397#c5) 🎉

**Pull request merged**
